name: actograph-v3

services:
  actograph-v3-front-electron:
    container_name: actograph-v3-front-electron
    image: actograph-v3-front-electron
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile.electron
    ports:
      - ${FRONT_DOCKER_PORT_EXPOSED:-8080}:${FRONT_DOCKER_PORT_EXPOSED:-8080}
    restart: 'unless-stopped'
    volumes:
      - ./../:/app/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority
    environment:
      - API_URL=${API_URL}
      - DOCKER_DEV=${DOCKER_DEV:-false}
      - FRONT_DOCKER_PORT_EXPOSED=${FRONT_DOCKER_PORT_EXPOSED:-8080}
      - APP_NAME=${APP_NAME}
      - DISPLAY=${DISPLAY:-:0}
    network_mode: "host"  # Use host network for X11
    command: bash -c "if [[ -z \"${DOCKER_DEV}\" ]]; then cd /app; yarn install; ./node_modules/.bin/quasar dev -m electron -- --no-sandbox; else tail -f /dev/null; fi"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536