FROM node:20.11.1

# Install dependencies for Electron
RUN apt-get update && apt-get install -y \
    libgtk-3-0 \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xvfb \
    libgbm-dev \
    x11-apps \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# We'll set the DISPLAY environment variable at runtime
WORKDIR /app 