/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by scripts/generate-indexes.js
 * Run `yarn generate:indexes` to regenerate.
 * 
 * Generated: 2026-02-12T13:23:12.375Z
 * Migrations found: 10
 * 
 * IMPORTANT: Migrations are listed in chronological order (by filename).
 */

import { Init1741279932330 } from '../../migrations/1741279932330-init';
import { addLicense1742079939246 } from '../../migrations/1742079939246-add-license';
import { dropTables1742245824090 } from '../../migrations/1742245824090-drop-tables';
import { addObservationModule1742245965719 } from '../../migrations/1742245965719-add-observation-module';
import { addProtocolItems1742460309452 } from '../../migrations/1742460309452-add-protocol-items';
import { newReadingFields1742551461889 } from '../../migrations/1742551461889-new-reading-fields';
import { addIndexes1742551502761 } from '../../migrations/1742551502761-add-indexes';
import { fix1742993904122 } from '../../migrations/1742993904122-fix';
import { addTempId1745247869971 } from '../../migrations/1745247869971-add-temp-id';
import { AddVideoPathAndModeToObservation1746000000000 } from '../../migrations/1746000000000-add-video-path-and-mode-to-observation';

// Export all migrations as an array for TypeORM configuration
// Order matters! Migrations are run in the order they appear in this array.
export const AllMigrations = [
  Init1741279932330,
  addLicense1742079939246,
  dropTables1742245824090,
  addObservationModule1742245965719,
  addProtocolItems1742460309452,
  newReadingFields1742551461889,
  addIndexes1742551502761,
  fix1742993904122,
  addTempId1745247869971,
  AddVideoPathAndModeToObservation1746000000000,
];
