/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This file is automatically generated by scripts/generate-indexes.js
 * Run `yarn generate:indexes` to regenerate.
 * 
 * Generated: 2026-01-25T14:33:46.227Z
 * Entities found: 7
 * 
 * IMPORTANT: Entities are sorted topologically based on their dependencies.
 * Entities that are referenced by other entities (e.g., UserJwt is used by User)
 * are listed first. This ordering is critical for TypeORM metadata resolution
 * when the API is bundled with esbuild.
 */

import { UserJwt } from '../general/auth-jwt/entities/user-jwt.entity';
import { License } from '../core/security/entities/license.entity';
import { Protocol } from '../core/observations/entities/protocol.entity';
import { Reading } from '../core/observations/entities/reading.entity';
import { Observation } from '../core/observations/entities/observation.entity';
import { User } from '../core/users/entities/user.entity';
import { ActivityGraph } from '../core/observations/entities/activity-graph.entity';

// Export all entities as an array for TypeORM configuration
// Order matters! Dependencies must be loaded before entities that reference them.
export const AllEntities = [
  UserJwt,
  License,
  Protocol,
  Reading,
  Observation,
  User,
  ActivityGraph,
];
